version: "3.3"
services:

mariadb-master:
  image: mariadb:latest
  ports:
   - '3306'
  volumes:
   - 'mariadb_master_data:/bitnami/mariadb'
  environment:
   - MARIADB_REPLICATION_MODE=master
   - MARIADB_REPLICATION_USER=repl_user
   - MARIADB_USER=php
   - MARIADB_DATABASE=notes
   - ALLOW_EMPTY_PASSWORD=yes
   - MARIADB_ROOT_PASSWORD=my_root_password
  volumes:
   - ./notes.sql:/docker-entrypoint-initdb.d/notes.sql
  networks:
   - app-network

 mariadb-slave:
  image: mariadb:latest
  ports:
   - '3306'
  depends_on:
   - mariadb-master
  environment:
   MARIADB_REPLICATION_MODE: slave
   MARIADB_REPLICATION_USER: repl_user
   MARIADB_USER: php
   MARIADB_DATABASE: notes
   MARIADB_MASTER_HOST: mariadb-master
   MARIADB_MASTER_PORT_NUMBER: 3306
   MARIADB_MASTER_ROOT_PASSWORD: root
   ALLOW_EMPTY_PASSWORD: yes
  volumes:
   - ./notes.sql:/docker-entrypoint-initdb.d/notes.sql
  networks:
   - app-network
  

 myphp:
  image: svenuq/45076396:a2
  restart: always
  depends_on:
   - mariadb-master
   - mariadb-slave
  ports:
   - "9000:9000"
  volumes:
   - ./UQNote:/var/www/html
  privileged: true
  links:
   - mariadb-master
  networks:
   - app-network

 mynginx:
  depends_on:
   - myphp
  image: nginx:latest
  restart: always
  ports:
   - "8080:80"
  volumes:
   - ./UQNote:/var/www/html
   - ./nginx.ini:/etc/nginx/conf.d/default.conf
   - ./php-fpm.conf:/etc/php/7.4/fpm/php-fpm.conf
   - ./www.conf:/etc/php/7.4/fpm/pool.d/www.conf
  links:
   - myphp:myphp
  privileged: true
  restart: always
  networks:
   - app-network


networks:
 app-network:
  driver: bridge
