version: "3.3"

services:

  mysql:
    image: mariadb:latest
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: MyDBRoot123
      MYSQL_DATABASE: php
      MYSQL_USER: php
      MYSQL_PASSWORD: php
    networks:
      - my-net

  myredis-master:
    image: 'bitnami/redis:latest'
    restart: always
    user: root
    ports:
      - '6379'
    environment:
      - REDIS_REPLICATION_MODE=master
      - REDIS_PASSWORD=my_master_password
    volumes:
      - './radis:/bitnami'
    networks:
      - my-net

  myredis-replica:
    image: 'bitnami/redis:latest'
    user: root
    restart: always
    ports:
      - '6379'
    depends_on:
      - myredis-master
    environment:
      - REDIS_REPLICATION_MODE=slave
      - REDIS_MASTER_HOST=myredis-master
      - REDIS_MASTER_PORT_NUMBER=6379
      - REDIS_MASTER_PASSWORD=my_master_password
      - REDIS_PASSWORD=my_replica_password
    networks:
      - my-net

  myphp:
    build: ./php
    restart: always
    expose:
      - "9000"
    volumes: 
      - ./UQnote:/var/www/html
    depends_on:
      - mysql
      - myredis-master
      - myredis-replica
    networks:
      - my-net

  mynginx:
    image: nginx
    restart: always
    volumes:
      - ./UQnote/nginx.ini:/etc/nginx/conf.d/default.conf
      - ./UQnote/php-fpm.conf:/etc/php/7.4/fpm/php-fpm.conf
      - ./UQnote/www.conf:/etc/php/7.4/fpm/pool.d/www.conf
      - ./UQnote:/var/www/html/
    ports:
      - "8080:80"
    depends_on:
      - myphp
    networks:
      - my-net

networks:
  my-net:
    driver: bridge