version: "3.3"
services:

 mariadb-master:
  image: mariadb:latest
  restart: always
  ports:
   - 3306:3306
  environment:
   MYSQL_ROOT_PASSWORD: root
   MYSQL_DATABASE: notes
  volumes:
   - ./master/my.cnf:/etc/mysql/my.cnf
   - ./notes.sql:/docker-entrypoint-initdb.d/notes.sql
 
 mariadb-slave:
  image: mariadb:latest
  depends_on: mariadb-master
  restart: always
  ports:
   - 3306:3307
  environment:
   MYSQL_ROOT_PASSWORD: root
   MYSQL_DATABASE: notes
  volumes:
   - ./slave/my.cnf:/etc/mysql/my.cnf
   - ./notes.sql:/docker-entrypoint-initdb.d/notes.sql

  

 myphp:
  image: svenuq/45076396:a2
  restart: always
  depends_on:
   - mysqlMaster
   - mysqlSlave
  ports:
   - "9000:9000"
  volumes:
   - ./UQNote:/var/www/html
  privileged: true
  links:
   - mysqlMaster
  networks:
   - app-network

 mynginx:
  depends_on:
   - myphp
  image: nginx:latest
  restart: always
  ports:
   - "8080:80"
  volumes:
   - ./UQNote:/var/www/html
   - ./nginx.ini:/etc/nginx/conf.d/default.conf
   - ./php-fpm.conf:/etc/php/7.4/fpm/php-fpm.conf
   - ./www.conf:/etc/php/7.4/fpm/pool.d/www.conf
  links:
   - myphp:myphp
  privileged: true
  restart: always
  networks:
   - app-network


networks:
 app-network:
  driver: bridge
