version: "3.3"
services:

 mysqlMaster:
  image: mariadb:latest
  restart: always
  environment:
   MASTER: 1
   SERVER_ID: 1
   REPLICATION_PASSWORD: MyDBRoot123
   MYSQL_ROOT_PASSWORD: MyDBRoot123
   MYSQL_DATABASE: notes
   MYSQL_USER: php
   MYSQL_PASSWORD: php
  volumes:
   - ./notes.sql:/docker-entrypoint-initdb.d/notes.sql
  ports:
   - "3306:3306"
  networks:
   - app-network

 mysqlSlave:
  image: mariadb:latest
  restart: always
  environment:
   SLAVE: 1
   SERVER_ID: 3
   REPLICATION_PASSWORD: MyDBRoot123
   MYSQL_ROOT_PASSWORD: MyDBRoot123
   MYSQL_DATABASE: notes
   MASTER_HOST: mysqlMaster
   MASTER_PORT: 3306
   MASTER_LOG_FILE: mysql-bin.000003
   MASTER_LOG_POS: 0
  volumes:
   - ./notes.sql:/docker-entrypoint-initdb.d/notes.sql
  ports:
   - "3307:3306"
  networks:
   - app-network
  

 myphp:
  image: svenuq/45076396:a2
  restart: always
  depends_on:
   - mysqlMaster
   - mysqlSlave
  ports:
   - "9000:9000"
  volumes:
   - ./UQNote:/var/www/html
  privileged: true
  links:
   - mysqlMaster
  networks:
   - app-network

 mynginx:
  depends_on:
   - myphp
  image: nginx:latest
  restart: always
  ports:
   - "8080:80"
  volumes:
   - ./UQNote:/var/www/html
   - ./nginx.ini:/etc/nginx/conf.d/default.conf
   - ./php-fpm.conf:/etc/php/7.4/fpm/php-fpm.conf
   - ./www.conf:/etc/php/7.4/fpm/pool.d/www.conf
  links:
   - myphp:myphp
  privileged: true
  restart: always
  networks:
   - app-network


networks:
 app-network:
  driver: bridge
