version: "3.3"

services:

  mysql:
    image: mariadb:latest
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: MyDBRoot123
      MYSQL_DATABASE: php
      MYSQL_USER: php
      MYSQL_PASSWORD: php
    networks:
      - my-net

  myphp:
    build: ./php
    restart: always
    expose:
      - "9000"
    volumes: 
      - ./src:/var/www/html
    depends_on:
      - mysql
      - myredis-master
      - myredis-replica
    networks:
      - my-net

  mynginx:
    image: nginx
    restart: always
    volumes:
      - ./src/nginx.ini:/etc/nginx/conf.d/default.conf
      - ./src/php-fpm.conf:/etc/php/7.4/fpm/php-fpm.conf
      - ./src/www.conf:/etc/php/7.4/fpm/pool.d/www.conf
      - ./src:/var/www/html/
    ports:
      - "8080:80"
    depends_on:
      - myphp
    networks:
      - my-net

networks:
  my-net:
    driver: bridge