version: '3.3'

services:
  mysql-master:
    image: mysql:latest
    restart: always
    environment:
      SERVER_ID: 1
      HOSTNAME: mysql-master
      MYSQL_DATABASE: notes
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./master:/var/lib/mysql
      - ./master/my.cnf:/etc/mysql/conf.d/custom.cnf
      - ./notes.sql:/docker-entrypoint-initdb.d/notes.sql
    ports:
      - 3306:3306
    networks:
      - app-network

  mysql-slave1:
    image: mysql:latest
    environment:
      SERVER_ID: 2
      MYSQL_DATABASE: notes
      MYSQL_ROOT_PASSWORD: root
    restart: always
    volumes:
      - ./slave1:/var/lib/mysql
      - ./slave1/my.cnf:/etc/mysql/conf.d/custom.cnf
      - ./notes.sql:/docker-entrypoint-initdb.d/notes.sql
    ports:
      - 3307:3306
    networks:
      - app-network

  mysql-slave2:
    image: mysql:latest
    environment:
      SERVER_ID: 3
      MYSQL_DATABASE: notes
      MYSQL_ROOT_PASSWORD: root
    restart: always
    volumes:
      - ./slave2:/var/lib/mysql
      - ./slave2/my.cnf:/etc/mysql/conf.d/custom.cnf
      - ./notes.sql:/docker-entrypoint-initdb.d/notes.sql
    ports:
      - 3308:3306
    networks:
      - app-network

 
  myphp:
    image: svenuq/45076396:a2
    restart: always
    depends_on:
      - mysql-master
      - mysql-slave1
      - mysql-slave2
    ports:
      - "9000:9000"
    volumes:
      - ./UQNote:/var/www/html
    privileged: true
    links:
      - mysql-master
    networks:
      - app-network

  mynginx:
    depends_on:
      - myphp
    image: nginx:latest
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./UQNote:/var/www/html
      - ./nginx.ini:/etc/nginx/conf.d/default.conf
      - ./php-fpm.conf:/etc/php/7.4/fpm/php-fpm.conf
      - ./www.conf:/etc/php/7.4/fpm/pool.d/www.conf
    links:
      - myphp:myphp
    privileged: true
    restart: always
    networks:
      - app-network


networks:
  app-network:
    driver: bridge
