version: '3.3'

services:
  mysql-master:
    image: mariadb:latest
    restart: always
    environment:
      HOSTNAME: mysql-master
      MYSQL_DATABASE: notes
      MYSQL_PASSWORD: php
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: php
    volumes:
      - ./master/data:/var/lib/mysql:rw
      - ./master/my.cnf:/etc/mysql/conf.d/custom.cnf:ro
      - ./notes.sql:/docker-entrypoint-initdb.d/notes.sql
    ports:
      - 3306:3306
    networks:
      - app-network

  mysql-slave:
    image: mariadb:latest
    environment:
      MYSQL_DATABASE: notes
      MYSQL_PASSWORD: php
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: slave
    restart: always
    volumes:
      - ./mysql-slave/data:/var/lib/mysql:rw
      - ./mysql-slave/my.cnf:/etc/mysql/conf.d/custom.cnf:ro
    ports:
      - 3307:3306
    networks:
      - app-network

 
  myphp:
    image: svenuq/45076396:a2
    restart: always
    depends_on:
      - mysql-master
      - mysql-slave
    ports:
      - "9000:9000"
    volumes:
      - ./UQNote:/var/www/html
    privileged: true
    links:
      - mysql-master
    networks:
      - app-network

  mynginx:
    depends_on:
      - myphp
    image: nginx:latest
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./UQNote:/var/www/html
      - ./nginx.ini:/etc/nginx/conf.d/default.conf
      - ./php-fpm.conf:/etc/php/7.4/fpm/php-fpm.conf
      - ./www.conf:/etc/php/7.4/fpm/pool.d/www.conf
    links:
      - myphp:myphp
    privileged: true
    restart: always
    networks:
      - app-network


networks:
  app-network:
    driver: bridge
