version: "3.3"
services:

 mysql:
  image: mariadb:latest
  restart: always
  environment:
   MYSQL_ROOT_PASSWORD: MyDBRoot123
   MYSQL_DATABASE: php
   MYSQL_USER: php
   MYSQL_PASSWORD: notes
  volumes:
   - ./UQnote:/var/lib/mysql
  ports:
   - "3306:3306"
  networks:
   - app-network

 myphp:
  image: svenuq/45076396:a2
  depends_on:
   - mysql
  ports:
   - "9000:9000"
  volumes:
   - ./UQnote:/var/www/html
  privileged: true
  links:
   - mysql:mysql
  networks:
   - app-network

 mynginx:
  depends_on:
   - myphp
  image: nginx:latest
  ports:
   - "8080:80"
  volumes:
   - ./UQnote:/var/www/html
   - ./nginx.ini:/etc/nginx/conf.d/default.conf
   - ./php-fpm.conf:/etc/php/7.4/fpm/php-fpm.conf
   - ./www.conf:/etc/php/7.4/fpm/pool.d/www.conf
  links:
   - myphp:myphp
  privileged: true
  restart: always
  networks:
   - app-network


networks:
 app-network:
  driver: bridge
