version: '3.3'

services:
  mysql-master:
    image: mariadb:latest
    restart: always
    environment:
      SERVER_ID: 1
      HOSTNAME: mysql-master
      MARIADB_REPLICATION_MODE: master
      MARIADB_REPLICATION_USER: repl
      MARIADB_REPLICATION_PASSWOR: '112233'
      MARIADB_ROOT_PASSWORD: root
      MYSQL_DATABASE: notes
      
    volumes:
      - ./master/data:/var/lib/mysql
      - ./master/my.cnf:/etc/mysql/conf.d/custom.cnf
      - ./notes.sql:/docker-entrypoint-initdb.d/notes.sql
    ports: 
      - "3306"
    networks:
      - app-network

  mysql-slave:
    image: mariadb:latest
    depends_on:
      - mysql-master
    environment:
      SERVER_ID: 2
      MARIADB_REPLICATION_MODE: slave
      MARIADB_REPLICATION_USER: repl
      MARIADB_REPLICATION_PASSWOR: '112233'
      MARIADB_DATABASE: notes
      MARIADB_ROOT_PASSWORD: root
      MARIADB_MASTER_HOST: mysql-master
      MARIADB_MASTER_ROOT_PASSWORD: root
    restart: always
    volumes:
      - ./slave/data:/var/lib/mysql
      - ./slave/my.cnf:/etc/mysql/conf.d/custom.cnf
      - ./notes.sql:/docker-entrypoint-initdb.d/notes.sql
    ports:
      - "3306"
    networks:
      - app-network


 
  myphp:
    image: svenuq/45076396:a2
    restart: always
    depends_on:
      - mysql-master
      - mysql-slave
    ports:
      - "9000"
    volumes:
      - ./UQNote:/var/www/html
    privileged: true
    links:
      - mysql-master
    networks:
      - app-network

  mynginx:
    depends_on:
      - myphp
    image: nginx:latest
    restart: always
    ports:
      - "80"
    volumes:
      - ./UQNote:/var/www/html
      - ./nginx.ini:/etc/nginx/conf.d/default.conf
      - ./php-fpm.conf:/etc/php/7.4/fpm/php-fpm.conf
      - ./www.conf:/etc/php/7.4/fpm/pool.d/www.conf
    links:
      - myphp:myphp
    privileged: true
    restart: always
    networks:
      - app-network


networks:
  app-network:
    driver: bridge
