version: "3.3"

services:

  mysql:
    image: mariadb:latest
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: MyDBRoot123
      MYSQL_DATABASE: php
      MYSQL_USER: php
      MYSQL_PASSWORD: php
    networks:
      - my-net

  myphp:
    build: ./php
    restart: always
    expose:
      - "9000"
    volumes: 
      - ./UQnote:/var/www/html
    depends_on:
      - mysql
    networks:
      - my-net
      
  phpmyadmin:
    image: phpmyadmin
    environment:
     - PMA_ARBITRARY=1
     - PMA_HOST=mysql
    restart: always
    ports:
     - "3307"
    depends_on:
      - mysql
    networks:
      - my-net
      
      

  mynginx:
    image: nginx
    restart: always
    volumes:
      - ./nginx.ini:/etc/nginx/conf.d/default.conf
      - ./php-fpm.conf:/etc/php/7.4/fpm/php-fpm.conf
      - ./www.conf:/etc/php/7.4/fpm/pool.d/www.conf
      - ./UQnote:/var/www/html/
    ports:
      - "8080:80"
    depends_on:
      - myphp
    networks:
      - my-net

networks:
  my-net:
    driver: bridge